/* ==========================================================================
   DocumenTI — dados de categorias e ferramentas
   Cada categoria tem: id, label (nome exibido), icon (glifo mono) e cor (var CSS)
   Cada item tem: name, desc, url, cat (id da categoria)
   ========================================================================== */

const CATEGORIES = [
  { id: "front",  label: "Front-end",              icon: "◆", color: "#1900FF" },
  { id: "back",   label: "Back-end",                icon: "◆", color: "#7C3AED" },
  { id: "db",     label: "Banco de Dados",           icon: "◆", color: "#0EA5E9" },
  { id: "mobile", label: "Mobile",                   icon: "◆", color: "#F97316" },
  { id: "test",   label: "Testes",                   icon: "◆", color: "#22C55E" },
  { id: "devops", label: "DevOps / CI-CD",           icon: "◆", color: "#EF4444" },
  { id: "auth",   label: "Autenticação",             icon: "◆", color: "#EAB308" },
  { id: "cms",    label: "CMS",                      icon: "◆", color: "#EC4899" },
  { id: "vcs",    label: "Controle de Versão",       icon: "◆", color: "#94A3B8" },
  { id: "pkg",    label: "Build & Pacotes",          icon: "◆", color: "#14B8A6" },
  { id: "ai",     label: "IA & Machine Learning",    icon: "◆", color: "#A855F7" },
  { id: "obs",    label: "Observabilidade",          icon: "◆", color: "#F43F5E" },
  { id: "deploy", label: "Deploy & Hosting",         icon: "◆", color: "#3B82F6" },
  { id: "tools",  label: "Ferramentas",              icon: "◆", color: "#64748B" },
];

const TOOLS = [
  // Front-end
  { cat: "front", name: "HTML", desc: "Linguagem de marcação base para estruturação de páginas web.", url: "https://developer.mozilla.org/en-US/docs/Web/HTML" },
  { cat: "front", name: "CSS", desc: "Linguagem de estilo para apresentação visual de páginas web.", url: "https://developer.mozilla.org/en-US/docs/Web/CSS" },
  { cat: "front", name: "JavaScript", desc: "Linguagem de programação usada para interatividade e lógica no navegador.", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
  { cat: "front", name: "TypeScript", desc: "Superset tipado de JavaScript que compila para JS puro.", url: "https://www.typescriptlang.org/docs/" },
  { cat: "front", name: "React", desc: "Biblioteca JavaScript para construção de interfaces de usuário.", url: "https://react.dev/" },
  { cat: "front", name: "Vue.js", desc: "Framework progressivo para criação de interfaces reativas.", url: "https://vuejs.org/guide/introduction.html" },
  { cat: "front", name: "Angular", desc: "Framework completo para construção de aplicações web SPA.", url: "https://angular.io/docs" },
  { cat: "front", name: "Svelte", desc: "Framework de front-end que compila componentes para código otimizado.", url: "https://svelte.dev/docs" },
  { cat: "front", name: "SvelteKit", desc: "Framework fullstack oficial construído sobre o Svelte.", url: "https://kit.svelte.dev/docs/introduction" },
  { cat: "front", name: "Next.js", desc: "Framework React para renderização SSR, rotas e APIs.", url: "https://nextjs.org/docs" },
  { cat: "front", name: "Nuxt.js", desc: "Framework Vue para renderização SSR e estrutura de projeto completa.", url: "https://nuxt.com/docs" },
  { cat: "front", name: "Astro", desc: "Framework focado em conteúdo com renderização estática por padrão.", url: "https://docs.astro.build/" },
  { cat: "front", name: "SolidJS", desc: "Biblioteca reativa de alta performance com sintaxe similar ao React.", url: "https://www.solidjs.com/docs/latest" },
  { cat: "front", name: "Qwik", desc: "Framework focado em resumability e carregamento instantâneo.", url: "https://qwik.dev/docs/" },
  { cat: "front", name: "Remix", desc: "Framework React fullstack focado em web fundamentals e UX.", url: "https://remix.run/docs" },
  { cat: "front", name: "Tailwind CSS", desc: "Framework CSS utilitário para estilização rápida e responsiva.", url: "https://tailwindcss.com/docs" },
  { cat: "front", name: "Bootstrap", desc: "Framework CSS popular com componentes responsivos e utilitários.", url: "https://getbootstrap.com/docs/5.0/getting-started/introduction/" },
  { cat: "front", name: "Sass", desc: "Pré-processador CSS com variáveis, nesting e mixins.", url: "https://sass-lang.com/documentation/" },
  { cat: "front", name: "PostCSS", desc: "Ferramenta para transformar CSS com plugins em JavaScript.", url: "https://postcss.org/" },
  { cat: "front", name: "Material UI", desc: "Componentes React baseados nas diretrizes do Material Design.", url: "https://mui.com/material-ui/getting-started/" },
  { cat: "front", name: "Chakra UI", desc: "Biblioteca de componentes acessíveis com tema personalizável.", url: "https://chakra-ui.com/docs/getting-started" },
  { cat: "front", name: "ShadCN/UI", desc: "Componentes acessíveis e reutilizáveis com suporte a Tailwind.", url: "https://ui.shadcn.com/docs" },
  { cat: "front", name: "Radix UI", desc: "Componentes UI acessíveis e sem estilos para React.", url: "https://www.radix-ui.com/primitives/docs/overview/introduction" },
  { cat: "front", name: "Framer Motion", desc: "Biblioteca de animações modernas e fluidas para React.", url: "https://www.framer.com/motion/" },
  { cat: "front", name: "GSAP", desc: "Biblioteca poderosa para animações de alta performance na web.", url: "https://gsap.com/docs/v3/" },
  { cat: "front", name: "Three.js", desc: "Biblioteca JavaScript para criação de gráficos 3D no navegador.", url: "https://threejs.org/docs/" },
  { cat: "front", name: "D3.js", desc: "Biblioteca para visualização de dados interativos com SVG e HTML.", url: "https://d3js.org/" },
  { cat: "front", name: "SVG", desc: "Gráficos vetoriais escaláveis usados em web para ícones e animações.", url: "https://developer.mozilla.org/en-US/docs/Web/SVG" },
  { cat: "front", name: "jQuery", desc: "Biblioteca JavaScript para manipulação de DOM e requisições AJAX.", url: "https://api.jquery.com/" },
  { cat: "front", name: "Alpine.js", desc: "Framework leve para adicionar interatividade com JavaScript direto no HTML.", url: "https://alpinejs.dev/start-here" },
  { cat: "front", name: "Lit", desc: "Biblioteca para criação de Web Components leves e rápidos.", url: "https://lit.dev/docs/" },
  { cat: "front", name: "Stencil", desc: "Compiler para criar Web Components reutilizáveis com padrão moderno.", url: "https://stenciljs.com/docs/introduction" },
  { cat: "front", name: "Vanilla JS", desc: "JavaScript puro, sem frameworks ou bibliotecas externas.", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
  { cat: "front", name: "React Hook Form", desc: "Biblioteca para formulários performáticos em React com validação integrada.", url: "https://react-hook-form.com/get-started" },
  { cat: "front", name: "Zod", desc: "Biblioteca de validação e parsing de esquemas com TypeScript first.", url: "https://zod.dev/" },
  { cat: "front", name: "Recharts", desc: "Biblioteca de gráficos reutilizáveis em React baseada em D3.", url: "https://recharts.org/en-US" },
  { cat: "front", name: "Lucide Icons", desc: "Conjunto de ícones bonitos e minimalistas para React.", url: "https://lucide.dev/guide/packages/lucide-react" },

  // Back-end
  { cat: "back", name: "Node.js", desc: "Ambiente de execução para JavaScript no servidor, baseado no V8.", url: "https://nodejs.org/en/docs" },
  { cat: "back", name: "Express", desc: "Framework web minimalista e flexível para Node.js.", url: "https://expressjs.com/en/4x/api.html" },
  { cat: "back", name: "NestJS", desc: "Framework Node.js com arquitetura modular baseada em TypeScript.", url: "https://docs.nestjs.com/" },
  { cat: "back", name: "Fastify", desc: "Framework web para Node.js focado em performance e extensibilidade.", url: "https://fastify.dev/docs/latest/" },
  { cat: "back", name: "Koa", desc: "Framework web minimalista e elegante criado pelos criadores do Express.", url: "https://koajs.com/" },
  { cat: "back", name: "Hapi", desc: "Framework para construção de aplicações e serviços robustos em Node.js.", url: "https://hapi.dev/api/" },
  { cat: "back", name: "Deno", desc: "Runtime moderno e seguro para JavaScript e TypeScript.", url: "https://docs.deno.com/" },
  { cat: "back", name: "Bun", desc: "Runtime JavaScript ultrarrápido com bundler, test runner e package manager.", url: "https://bun.sh/docs" },
  { cat: "back", name: "Python", desc: "Linguagem de programação versátil usada em backend, IA e automação.", url: "https://docs.python.org/3/" },
  { cat: "back", name: "Django", desc: "Framework web de alto nível para Python com foco em rapidez e segurança.", url: "https://docs.djangoproject.com/en/stable/" },
  { cat: "back", name: "Flask", desc: "Microframework para web com Python, leve e extensível.", url: "https://flask.palletsprojects.com/en/latest/" },
  { cat: "back", name: "FastAPI", desc: "Framework moderno e rápido para APIs com Python baseado em type hints.", url: "https://fastapi.tiangolo.com/" },
  { cat: "back", name: "Ruby on Rails", desc: "Framework web completo e produtivo com linguagem Ruby.", url: "https://guides.rubyonrails.org/" },
  { cat: "back", name: "PHP", desc: "Linguagem de programação para desenvolvimento de aplicações web dinâmicas.", url: "https://www.php.net/docs.php" },
  { cat: "back", name: "Laravel", desc: "Framework PHP elegante com sintaxe expressiva e ferramentas modernas.", url: "https://laravel.com/docs" },
  { cat: "back", name: "Spring Boot", desc: "Framework Java para construção de aplicações standalone e produtivas.", url: "https://docs.spring.io/spring-boot/index.html" },
  { cat: "back", name: ".NET", desc: "Plataforma da Microsoft para desenvolvimento de aplicações escaláveis e seguras.", url: "https://learn.microsoft.com/en-us/dotnet/" },
  { cat: "back", name: "Go (Golang)", desc: "Linguagem de programação criada pelo Google, eficiente e concorrente.", url: "https://go.dev/doc/" },
  { cat: "back", name: "Rust", desc: "Linguagem focada em performance e segurança de memória, ideal para backend.", url: "https://doc.rust-lang.org/" },
  { cat: "back", name: "Java", desc: "Linguagem orientada a objetos amplamente usada em sistemas corporativos.", url: "https://docs.oracle.com/en/java/" },
  { cat: "back", name: "GraphQL", desc: "Query language para APIs e runtime para atender queries com dados existentes.", url: "https://graphql.org/learn/" },
  { cat: "back", name: "Apollo Server", desc: "Servidor GraphQL fácil de usar com suporte para diversos bancos e linguagens.", url: "https://www.apollographql.com/docs/apollo-server/" },
  { cat: "back", name: "Hasura", desc: "Engine GraphQL instantânea sobre banco PostgreSQL com controle de permissões.", url: "https://hasura.io/docs/latest/" },
  { cat: "back", name: "gRPC", desc: "Framework de chamada de procedimento remoto de alto desempenho da Google.", url: "https://grpc.io/docs/" },
  { cat: "back", name: "REST API", desc: "Arquitetura de API baseada em recursos acessados por métodos HTTP.", url: "https://restfulapi.net/" },
  { cat: "back", name: "WebSockets", desc: "Protocolo para comunicação bidirecional contínua entre cliente e servidor.", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
  { cat: "back", name: "Socket.IO", desc: "Biblioteca para aplicações em tempo real usando WebSockets e fallback.", url: "https://socket.io/docs/v4/" },

  // Banco de Dados
  { cat: "db", name: "PostgreSQL", desc: "Sistema de banco de dados relacional open source avançado.", url: "https://www.postgresql.org/docs/" },
  { cat: "db", name: "MySQL", desc: "Um dos bancos de dados relacionais mais populares no mundo.", url: "https://dev.mysql.com/doc/" },
  { cat: "db", name: "SQLite", desc: "Banco de dados relacional leve e incorporável em aplicações locais.", url: "https://www.sqlite.org/docs.html" },
  { cat: "db", name: "MongoDB", desc: "Banco de dados NoSQL orientado a documentos e altamente escalável.", url: "https://www.mongodb.com/docs/" },
  { cat: "db", name: "Redis", desc: "Banco de dados em memória, usado como cache ou message broker.", url: "https://redis.io/docs/latest/" },
  { cat: "db", name: "Firebase", desc: "Plataforma do Google com banco, autenticação e hosting como serviço.", url: "https://firebase.google.com/docs" },
  { cat: "db", name: "Supabase", desc: "Alternativa open source ao Firebase baseada em PostgreSQL.", url: "https://supabase.com/docs" },
  { cat: "db", name: "Prisma", desc: "ORM moderno para Node.js e TypeScript, com foco em performance e segurança.", url: "https://www.prisma.io/docs" },
  { cat: "db", name: "TypeORM", desc: "ORM para TypeScript e JavaScript com suporte a múltiplos bancos.", url: "https://typeorm.io/" },
  { cat: "db", name: "Sequelize", desc: "ORM baseado em Promises para Node.js com suporte a SQL.", url: "https://sequelize.org/docs/v6/" },
  { cat: "db", name: "Mongoose", desc: "ODM para Node.js e MongoDB com schemas e validações.", url: "https://mongoosejs.com/docs/" },
  { cat: "db", name: "Amazon DynamoDB", desc: "Banco de dados NoSQL gerenciado e altamente escalável da AWS.", url: "https://docs.aws.amazon.com/dynamodb/" },
  { cat: "db", name: "Neon", desc: "Postgres serverless com branching de banco de dados.", url: "https://neon.tech/docs/introduction" },
  { cat: "db", name: "PlanetScale", desc: "Plataforma de banco de dados MySQL serverless com branching.", url: "https://planetscale.com/docs" },

  // Mobile
  { cat: "mobile", name: "React Native", desc: "Framework para criar apps nativos iOS e Android com React.", url: "https://reactnative.dev/docs/getting-started" },
  { cat: "mobile", name: "Flutter", desc: "SDK do Google para apps nativos multiplataforma com Dart.", url: "https://docs.flutter.dev/" },
  { cat: "mobile", name: "Expo", desc: "Plataforma que simplifica o desenvolvimento com React Native.", url: "https://docs.expo.dev/" },
  { cat: "mobile", name: "SwiftUI", desc: "Framework declarativo da Apple para interfaces em iOS/macOS.", url: "https://developer.apple.com/documentation/swiftui/" },
  { cat: "mobile", name: "Jetpack Compose", desc: "Toolkit moderno do Google para UI nativa Android com Kotlin.", url: "https://developer.android.com/jetpack/compose/documentation" },
  { cat: "mobile", name: "Kotlin", desc: "Linguagem moderna e concisa oficial para desenvolvimento Android.", url: "https://kotlinlang.org/docs/home.html" },
  { cat: "mobile", name: "Ionic", desc: "Framework para apps híbridos usando tecnologias web.", url: "https://ionicframework.com/docs" },

  // Testes
  { cat: "test", name: "Jest", desc: "Framework de testes para JavaScript com foco em simplicidade.", url: "https://jestjs.io/docs/getting-started" },
  { cat: "test", name: "Vitest", desc: "Framework de testes rápido e moderno para projetos Vite.", url: "https://vitest.dev/guide/" },
  { cat: "test", name: "Testing Library", desc: "Utilitários para testar componentes focados no comportamento do usuário.", url: "https://testing-library.com/docs/" },
  { cat: "test", name: "Mocha", desc: "Framework de testes JavaScript flexível e extensível.", url: "https://mochajs.org/" },
  { cat: "test", name: "Chai", desc: "Biblioteca de asserção para testes em JavaScript com Mocha.", url: "https://www.chaijs.com/" },
  { cat: "test", name: "Cypress", desc: "Ferramenta de testes end-to-end para aplicações web modernas.", url: "https://docs.cypress.io/" },
  { cat: "test", name: "Playwright", desc: "Automação para testes de navegadores com suporte a múltiplos browsers.", url: "https://playwright.dev/docs/intro" },
  { cat: "test", name: "Selenium", desc: "Framework para automação de navegadores com diversas linguagens.", url: "https://www.selenium.dev/documentation/" },

  // DevOps / CI-CD
  { cat: "devops", name: "Docker", desc: "Plataforma de containers para empacotar e distribuir aplicações.", url: "https://docs.docker.com/" },
  { cat: "devops", name: "Docker Compose", desc: "Ferramenta para definir e gerenciar múltiplos containers com um arquivo YAML.", url: "https://docs.docker.com/compose/" },
  { cat: "devops", name: "Kubernetes", desc: "Orquestrador de containers para deploy, escala e gestão automatizada.", url: "https://kubernetes.io/docs/home/" },
  { cat: "devops", name: "GitHub Actions", desc: "Automatização de workflows com CI/CD no GitHub.", url: "https://docs.github.com/en/actions" },
  { cat: "devops", name: "GitLab CI/CD", desc: "Pipeline CI/CD integrado ao GitLab com automações completas.", url: "https://docs.gitlab.com/ee/ci/" },
  { cat: "devops", name: "Jenkins", desc: "Ferramenta open-source de automação e integração contínua.", url: "https://www.jenkins.io/doc/" },
  { cat: "devops", name: "Ansible", desc: "Automação de configuração e gerenciamento de servidores.", url: "https://docs.ansible.com/" },
  { cat: "devops", name: "Terraform", desc: "Infraestrutura como código para provisionar recursos em nuvem.", url: "https://developer.hashicorp.com/terraform/docs" },
  { cat: "devops", name: "Nginx", desc: "Servidor web e proxy reverso de alto desempenho.", url: "https://nginx.org/en/docs/" },
  { cat: "devops", name: "Apache", desc: "Servidor HTTP robusto e extensível usado em milhões de servidores web.", url: "https://httpd.apache.org/docs/" },

  // Autenticação
  { cat: "auth", name: "Auth0", desc: "Plataforma de autenticação e autorização com suporte a OAuth e JWT.", url: "https://auth0.com/docs" },
  { cat: "auth", name: "Firebase Auth", desc: "Serviço de autenticação do Firebase com suporte a múltiplos métodos.", url: "https://firebase.google.com/docs/auth" },
  { cat: "auth", name: "Clerk", desc: "Solução moderna de autenticação e gerenciamento de usuários.", url: "https://clerk.com/docs" },
  { cat: "auth", name: "NextAuth.js", desc: "Biblioteca de autenticação para aplicações Next.js.", url: "https://authjs.dev/" },
  { cat: "auth", name: "Passport.js", desc: "Middleware de autenticação flexível para Node.js.", url: "https://www.passportjs.org/docs/" },
  { cat: "auth", name: "OAuth 2.0", desc: "Padrão de autenticação e autorização para aplicações seguras.", url: "https://oauth.net/2/" },
  { cat: "auth", name: "JWT", desc: "JSON Web Token: método seguro para transmitir informações entre partes.", url: "https://jwt.io/introduction" },

  // CMS
  { cat: "cms", name: "WordPress", desc: "CMS popular para criação e gerenciamento de sites.", url: "https://wordpress.org/documentation/" },
  { cat: "cms", name: "Strapi", desc: "Headless CMS open-source para APIs rápidas e flexíveis.", url: "https://docs.strapi.io/" },
  { cat: "cms", name: "Sanity", desc: "CMS headless com foco em conteúdo estruturado e em tempo real.", url: "https://www.sanity.io/docs" },
  { cat: "cms", name: "Contentful", desc: "Plataforma headless CMS baseada em API para gestão de conteúdo.", url: "https://www.contentful.com/developers/docs/" },
  { cat: "cms", name: "DatoCMS", desc: "Headless CMS baseado em GraphQL para sites estáticos e dinâmicos.", url: "https://www.datocms.com/docs" },
  { cat: "cms", name: "Payload CMS", desc: "Headless CMS open-source em TypeScript, code-first.", url: "https://payloadcms.com/docs" },

  // Controle de Versão
  { cat: "vcs", name: "Git", desc: "Sistema de controle de versão distribuído padrão da indústria.", url: "https://git-scm.com/doc" },
  { cat: "vcs", name: "GitHub", desc: "Plataforma de hospedagem de código com colaboração e CI/CD.", url: "https://docs.github.com/" },
  { cat: "vcs", name: "GitLab", desc: "Plataforma DevOps completa com repositórios e pipelines integrados.", url: "https://docs.gitlab.com/" },
  { cat: "vcs", name: "Bitbucket", desc: "Hospedagem de repositórios Git da Atlassian com integração Jira.", url: "https://support.atlassian.com/bitbucket-cloud/" },

  // Build & Pacotes
  { cat: "pkg", name: "npm", desc: "Gerenciador de pacotes padrão do Node.js.", url: "https://docs.npmjs.com/" },
  { cat: "pkg", name: "Yarn", desc: "Gerenciador de pacotes rápido e confiável para JavaScript.", url: "https://yarnpkg.com/getting-started" },
  { cat: "pkg", name: "pnpm", desc: "Gerenciador de pacotes rápido e eficiente em espaço em disco.", url: "https://pnpm.io/motivation" },
  { cat: "pkg", name: "Vite", desc: "Empacotador moderno e rápido para aplicações frontend.", url: "https://vite.dev/guide/" },
  { cat: "pkg", name: "Webpack", desc: "Empacotador de módulos JavaScript com suporte a loaders e plugins.", url: "https://webpack.js.org/concepts/" },
  { cat: "pkg", name: "Rollup", desc: "Empacotador de módulos ES focado em bibliotecas.", url: "https://rollupjs.org/introduction/" },
  { cat: "pkg", name: "esbuild", desc: "Bundler e minificador JavaScript extremamente rápido, escrito em Go.", url: "https://esbuild.github.io/" },
  { cat: "pkg", name: "Turborepo", desc: "Sistema de build de alta performance para monorepos JavaScript/TypeScript.", url: "https://turbo.build/repo/docs" },
  { cat: "pkg", name: "Babel", desc: "Transpilador JavaScript para usar recursos modernos em navegadores antigos.", url: "https://babeljs.io/docs/" },
  { cat: "pkg", name: "ESLint", desc: "Ferramenta para análise e padronização de código JavaScript/TypeScript.", url: "https://eslint.org/docs/latest/" },
  { cat: "pkg", name: "Prettier", desc: "Formatador de código para garantir consistência de estilo.", url: "https://prettier.io/docs/en/index.html" },

  // IA & Machine Learning
  { cat: "ai", name: "Claude API (Anthropic)", desc: "API para integrar os modelos Claude em produtos e agentes.", url: "https://docs.claude.com/" },
  { cat: "ai", name: "OpenAI API", desc: "API para modelos GPT, embeddings, áudio e visão computacional.", url: "https://platform.openai.com/docs" },
  { cat: "ai", name: "LangChain", desc: "Framework para orquestrar aplicações com LLMs, agentes e RAG.", url: "https://python.langchain.com/docs/introduction/" },
  { cat: "ai", name: "Hugging Face", desc: "Hub de modelos, datasets e bibliotecas open-source de IA.", url: "https://huggingface.co/docs" },
  { cat: "ai", name: "Ollama", desc: "Execução local de modelos de linguagem open-source.", url: "https://github.com/ollama/ollama/tree/main/docs" },
  { cat: "ai", name: "TensorFlow", desc: "Plataforma open-source do Google para machine learning.", url: "https://www.tensorflow.org/api_docs" },
  { cat: "ai", name: "PyTorch", desc: "Framework de deep learning flexível e amplamente adotado.", url: "https://pytorch.org/docs/stable/index.html" },

  // Observabilidade
  { cat: "obs", name: "Sentry", desc: "Monitoramento de erros e performance em tempo real.", url: "https://docs.sentry.io/" },
  { cat: "obs", name: "Grafana", desc: "Plataforma de visualização e dashboards para métricas.", url: "https://grafana.com/docs/grafana/latest/" },
  { cat: "obs", name: "Prometheus", desc: "Sistema de monitoramento e alertas com banco de séries temporais.", url: "https://prometheus.io/docs/introduction/overview/" },
  { cat: "obs", name: "Datadog", desc: "Plataforma de observabilidade completa para infraestrutura e apps.", url: "https://docs.datadoghq.com/" },
  { cat: "obs", name: "New Relic", desc: "Monitoramento de performance de aplicações (APM) full-stack.", url: "https://docs.newrelic.com/" },

  // Deploy & Hosting
  { cat: "deploy", name: "Vercel", desc: "Plataforma de deploy otimizada para Next.js e frontend moderno.", url: "https://vercel.com/docs" },
  { cat: "deploy", name: "Netlify", desc: "Plataforma de deploy contínuo para sites estáticos e JAMstack.", url: "https://docs.netlify.com/" },
  { cat: "deploy", name: "Railway", desc: "Plataforma de deploy simplificada para apps e bancos de dados.", url: "https://docs.railway.com/" },
  { cat: "deploy", name: "Render", desc: "Nuvem unificada para hospedar sites, APIs e bancos de dados.", url: "https://render.com/docs" },
  { cat: "deploy", name: "Heroku", desc: "Plataforma cloud clássica para deploy simplificado de apps.", url: "https://devcenter.heroku.com/" },
  { cat: "deploy", name: "AWS", desc: "Serviços de nuvem da Amazon, incluindo computação, storage e banco.", url: "https://docs.aws.amazon.com/" },
  { cat: "deploy", name: "Google Cloud", desc: "Plataforma de nuvem do Google com serviços de IA, dados e compute.", url: "https://cloud.google.com/docs" },
  { cat: "deploy", name: "Microsoft Azure", desc: "Plataforma de nuvem da Microsoft para apps e infraestrutura.", url: "https://learn.microsoft.com/en-us/azure/" },
  { cat: "deploy", name: "Cloudflare Pages", desc: "Hospedagem de sites estáticos com CDN global da Cloudflare.", url: "https://developers.cloudflare.com/pages/" },

  // Ferramentas
  { cat: "tools", name: "Postman", desc: "Plataforma para testar APIs REST e GraphQL com interface visual.", url: "https://learning.postman.com/docs/getting-started/introduction/" },
  { cat: "tools", name: "Insomnia", desc: "Cliente REST/GraphQL leve para testar e depurar APIs.", url: "https://docs.insomnia.rest/" },
  { cat: "tools", name: "Figma", desc: "Ferramenta de design colaborativa baseada na web.", url: "https://help.figma.com/hc/en-us" },
  { cat: "tools", name: "Swagger / OpenAPI", desc: "Especificação e ferramentas para documentação e testes de APIs.", url: "https://swagger.io/docs/" },
  { cat: "tools", name: "Storybook", desc: "Ambiente para desenvolver e documentar componentes de UI isoladamente.", url: "https://storybook.js.org/docs" },
  { cat: "tools", name: "VS Code", desc: "Editor de código gratuito e extensível da Microsoft.", url: "https://code.visualstudio.com/docs" },
];
